=== clarin-eric/standards/SIS/clarin/schemas/recommendation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:annotation>
        <xs:documentation xml:lang="en">This schema defines the structure of the recommendation
            files that reside under data/recommendations/. Mostly auto-derived thru the magic of
            oXygen.</xs:documentation>
    </xs:annotation>
    <xs:element name="recommendation">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="header"/>
                <xs:element ref="formats"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="header">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="title" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="url" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="lastUpdateCommitID" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="exportDate" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="filter" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="title" type="xs:string"/>
    <xs:element name="url" type="xs:anyURI">
        <xs:annotation>
            <xs:documentation>Element inserted into exports, to document where they came from.</xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="lastUpdateCommitID" type="xs:string">
        <xs:annotation>
            <xs:documentation>Element auto-inserted upon committing the file into the repository. It
                will not appear in exports from aggregated lists in the SIS.</xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="exportDate" type="xs:string">
        <xs:annotation>
            <xs:documentation>Element present in exports from the SIS; it encodes a standardized
                date string of the export.</xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="filter">
        <xs:annotation>
            <xs:documentation>Element present in exports from aggregated and filtered lists in the
                SIS.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="centre" minOccurs="0"/>
                <xs:element ref="domain" minOccurs="0"/>
                <xs:element ref="level" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="centre" type="xs:string"/>
    <xs:element name="domain">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <!--Annotation-->
                <xs:enumeration value="Audiovisual Annotation">
                    <xs:annotation>
                        <xs:documentation>Annotations of audiovisual sources, usually including a
                            basic rendering of the spoken content (transcription) and sometimes
                            further annotation.</xs:documentation>
                    </xs:annotation>
                </xs:enumeration>
                <xs:enumeration value="Image Annotation">
                    <xs:annotation>
                        <xs:documentation>Annotations of image sources.</xs:documentation>
                    </xs:annotation>
                </xs:enumeration>
                <xs:enumeration value="Text Annotation">
                    <xs:annotation>
                        <xs:documentation>Annotations of textual sources/written text, with the
                            original text included or as stand-off.</xs:documentation>
                    </xs:annotation>
                </xs:enumeration>
                <!--Data/Resource Description-->
                <xs:enumeration value="Catalogue Metadata">
                    <xs:annotation>
                        <xs:documentation>Basic structured information for discoverability and
                            general description, to be openly provided for
                            harvesting.</xs:documentation>
                    </xs:annotation>
                </xs:enumeration>
                <xs:enumeration value="Contextual Information">
                    <xs:annotation>
                        <xs:documentation>Structured information on the communicative event or text
                            and its creators (i.e. participants or authors) relevant for
                            analysis.</xs:documentation>
                    </xs:annotation>
                </xs:enumeration>
                <xs:enumeration value="Documentation">
                    <xs:annotation>
                        <xs:documentation>Unstructured documentation of the resource and its parts
                            such as corpus or annotation guidelines.</xs:documentation>
                    </xs:annotation>
                </xs:enumeration>
                <xs:enumeration value="Metadata">
                    <xs:annotation>
                        <xs:documentation>Comprehensive structured information including
                            descriptive, structural and administrative metadata. See the National
                            Information Standards Organization primer on metadata for further
                            hints.</xs:documentation>
                    </xs:annotation>
                </xs:enumeration>
                <!--Databases-->
                <xs:enumeration value="Geodata">
                    <xs:annotation>
                        <xs:documentation>Information on geographic locations.</xs:documentation>
                    </xs:annotation>
                </xs:enumeration>
                <xs:enumeration value="Language Description">
                    <xs:annotation>
                        <xs:documentation>Structured or unstructured descriptions of linguistic
                            varieties or phenomena, typological databases, etc.</xs:documentation>
                    </xs:annotation>
                </xs:enumeration>
                <xs:enumeration value="Lexical Resource">
                    <xs:annotation>
                        <xs:documentation>Structured (item-based) resources for lexical and/or
                            conceptual information on units of language (e.g. wordlists, lexicons,
                            WordNets etc.)</xs:documentation>
                    </xs:annotation>
                </xs:enumeration>
                <xs:enumeration value="Statistical Data">
                    <xs:annotation>
                        <xs:documentation>Data from surveys and tests in numeric
                            formats.</xs:documentation>
                    </xs:annotation>
                </xs:enumeration>
                <!--Source Data-->
                <xs:enumeration value="Audiovisual Source Language Data">
                    <xs:annotation>
                        <xs:documentation>Audio or video recordings providing spoken/multimodal or
                            signed language data for research purposes.</xs:documentation>
                    </xs:annotation>
                </xs:enumeration>
                <xs:enumeration value="Contextual Data">
                    <xs:annotation>
                        <xs:documentation>Images (photos or drawings) or documents relevant to the
                            communicative event or text but not part of the source language
                            data.</xs:documentation>
                    </xs:annotation>
                </xs:enumeration>
                <xs:enumeration value="Image Source Language Data">
                    <xs:annotation>
                        <xs:documentation>Digitized images of analogue sources of written language
                            data for research purposes (e.g. facsimiles, scans of handwriting,
                            photos of inscriptions).</xs:documentation>
                    </xs:annotation>
                </xs:enumeration>
                <xs:enumeration value="Textual Source Language Data">
                    <xs:annotation>
                        <xs:documentation>Written unstructured/plain text or originally structured
                            text (e.g. HTML) without linguistic or other mark-up added for research
                            purposes.</xs:documentation>
                    </xs:annotation>
                </xs:enumeration>
                <!--Uncategorized-->
                <xs:enumeration value="Other">
                    <xs:annotation>
                        <xs:documentation>Any other function that cannot be included in an existing
                            domain. The content of this domain will be periodically examined for
                            potential patterns that may give rise to new domains.</xs:documentation>
                    </xs:annotation>
                </xs:enumeration>
                <xs:enumeration value="Tool Support">
                    <xs:annotation>
                        <xs:documentation>Tool-related formats required for specific functionality
                            of the tool or reliable reuse of resources (e.g. tagsets, annotation
                            schemes, vocabularies, language models, parameter files, and other
                            specifications or settings)</xs:documentation>
                    </xs:annotation>
                </xs:enumeration>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="level">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="recommended"/>
                <xs:enumeration value="acceptable"/>
                <xs:enumeration value="deprecated"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="formats">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="format"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="format">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="domain"/>
                <xs:element ref="level"/>
                <xs:element minOccurs="0" ref="comment"/>
            </xs:sequence>
            <xs:attribute name="id" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="comment">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="a"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="i"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="code"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="a">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="href" use="required" type="xs:anyURI"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="i">
        <xs:simpleType>
            <xs:restriction base="xs:string"/>
        </xs:simpleType>
    </xs:element>
    <xs:element name="code">
        <xs:simpleType>
            <xs:restriction base="xs:string"/>
        </xs:simpleType>
    </xs:element>
    
</xs:schema>

=== clarin-eric/standards/SIS/clarin/data/recommendations/LAC-recommendation.xml
<recommendation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../schemas/recommendation.xsd">
    <header>
        <lastUpdateCommitID>618886ee0379878a233cf83b6f4a2d66b3b69d59</lastUpdateCommitID>
        <filter>
         <centre>LAC</centre>
      </filter>
    </header>
    <formats>
        <format id="fCMDI">
            <domain>Metadata</domain>
            <level>recommended</level>
            <comment>Profile <a href="http://catalog.clarin.eu/ds/ComponentRegistry/rest/registry/profiles/clarin.eu:cr1:p_147513601619/xsd">BLAM-bundle-repository-v0.14</a></comment>
        </format>
        <format id="fXML">
            <domain>Metadata</domain>
            <level>acceptable</level>
        </format>
        <format id="fCMDI">
            <domain>Metadata</domain>
            <level>acceptable</level>
        </format>
        <format id="fCSV">
            <domain>Metadata</domain>
            <level>acceptable</level>
            <comment>preferably with <a href="https://www.w3.org/TR/2015/REC-tabular-metadata-20151217/">W3C Metadata for Tabular Data</a> annotations</comment>
        </format>
        <format id="fELAN">
            <domain>Audiovisual Annotation</domain>
            <level>recommended</level>
        </format>
        <format id="fEXB">
            <domain>Audiovisual Annotation</domain>
            <level>acceptable</level>
        </format>
        <format id="fEXS">
            <domain>Audiovisual Annotation</domain>
            <level>acceptable</level>
        </format>
        <format id="fPraat">
            <domain>Audiovisual Annotation</domain>
            <level>acceptable</level>
        </format>
        <format id="fFLEx">
            <domain>Audiovisual Annotation</domain>
            <level>acceptable</level>
        </format>
        <format id="fToolbox">
            <domain>Audiovisual Annotation</domain>
            <level>acceptable</level>
            <comment>Toolbox files are still acceptable, but the format itself has proven to be problematic and should be avoided if possible. </comment>
        </format>
        <format id="fTEISpoken">
            <domain>Audiovisual Annotation</domain>
            <level>recommended</level>
        </format>
        <format id="fTEI">
            <domain>Audiovisual Annotation</domain>
            <level>recommended</level>
        </format>
        <format id="fWave">
            <domain>Audiovisual Source Language Data</domain>
            <level>recommended</level>
            <comment>LPCM audio (preferred sampling rate 48 kHz and bit depth 16 bit)</comment>
        </format>
        <format id="fMP4">
            <domain>Audiovisual Source Language Data</domain>
            <level>recommended</level>
            <comment>Video codec h.264 (preferred profile: main, level: 4.0, 1080p, 30fps), Audio encoding AAC (LC) (preferred sampling rate 48 kHz and bit rate 128â€“384 kbps)</comment>
        </format>
        <format id="fMOV">
            <domain>Audiovisual Source Language Data</domain>
            <level>recommended</level>
            <comment>Video codec h.264 (preferred profile: main, level: 4.0, 1080p, 30fps), Audio encoding LPCM (preferred sampling rate 48 kHz and bit depth 16 bit)</comment>
        </format>
        <format id="fPDFA">
            <domain>Contextual Data</domain>
            <level>recommended</level>
        </format>
        <format id="fTextPlain">
            <domain>Contextual Data</domain>
            <level>recommended</level>
            <comment>UTF-8 encoding</comment>
        </format>
        <format id="fXHTML">
            <domain>Contextual Data</domain>
            <level>recommended</level>
        </format>
        <format id="fTIFF">
            <domain>Contextual Data</domain>
            <level>recommended</level>
        </format>
        <format id="fJP2">
            <domain>Contextual Data</domain>
            <level>recommended</level>
        </format>
        <format id="fPNG">
            <domain>Contextual Data</domain>
            <level>acceptable</level>
        </format>
        <format id="fJPEG">
            <domain>Contextual Data</domain>
            <level>acceptable</level>
        </format>
    </formats>
</recommendation>

=== clarin-eric/standards/SIS/clarin/data/recommendations/CLARIN-LV-recommendation.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="../../schemas/recommendation.xsd" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?> 
<recommendation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../schemas/recommendation.xsd">
    <header>
        <lastUpdateCommitID>56edd195d9ed1d5bc7c2d984fac74a0c14801520</lastUpdateCommitID>
        <filter>
            <centreID>CLARIN-LV</centreID>
        </filter>
        <respStmt>
            <name>Roberts DarÄ£is</name>
            <link>https://github.com/Skriptotajs</link>
            <reviewDate>2025-09-10</reviewDate>
        </respStmt>
        <centre id="CLARIN-LV" deposition="1">
        <centreName>CLARIN Centre of Latvian language resources and tools</centreName>
        <registryLink registry="CLARIN" uri="https://centres.clarin.eu/centre/68"/>
        <nodeInfo>
          <ri status="B-centre">CLARIN</ri>
        </nodeInfo>
      </centre>
    </header>
    <info>
        <p>
            This page lists the recommended file formats for depositing materials in CLARIN-LV.  
            For more information, see the pages on  
            <a href="https://repository.clarin.lv/repository/xmlui/page/deposit" target="_blank">how to deposit</a> or  
            the <a href="https://repository.clarin.lv/repository/xmlui/page/item-lifecycle" target="_blank">lifecycle of deposited items</a>.
        </p>
        <p>
            For further details, please visit our <a href="https://repository.clarin.lv/repository/xmlui/page/about" target="_blank">About section and policies</a>.
        </p>
    </info>
    <formats>
        <format id="fAAC">
            <domain>Audiovisual Source Language Data</domain>
            <level>acceptable</level>
        </format>
        <format id="fAVI">
            <domain>Audiovisual Source Language Data</domain>
            <level>acceptable</level>
        </format>
        <format id="fBMP">
            <domain>Image Source Language Data</domain>
            <level>acceptable</level>
        </format>
        <format id="fCMDI">
            <domain>Metadata</domain>
            <level>recommended</level>
        </format>
        <format id="fCoNLL-U">
            <domain>Text Annotation</domain>
            <level>recommended</level>
        </format>
        <format id="fCSV">
            <domain>Text Annotation</domain>
            <level>acceptable</level>
            <comment>UTF-8 character encoding required</comment>
        </format>
        <format id="fCSV">
            <domain>Metadata</domain>
            <level>recommended</level>
            <comment>UTF-8 character encoding required</comment>
        </format>
        <format id="fDOC">
            <domain>Documentation</domain>
            <level>discouraged</level>
        </format>
        <format id="fDOC">
            <domain>Textual Source Language Data</domain>
            <level>discouraged</level>
        </format>
        <format id="fDOC">
            <domain>Metadata</domain>
            <level>discouraged</level>
        </format>
        <format id="fDOCX">
            <domain>Textual Source Language Data</domain>
            <level>discouraged</level>
        </format>
        <format id="fDOCX">
            <domain>Audiovisual Annotation</domain>
            <level>discouraged</level>
        </format>
        <format id="fDOCX">
            <domain>Metadata</domain>
            <level>discouraged</level>
        </format>
        <format id="fDOCX">
            <domain>Documentation</domain>
            <level>discouraged</level>
        </format>
        <format id="fEAF">
            <domain>Audiovisual Annotation</domain>
            <level>recommended</level>
        </format>
        <format id="fFLAC">
            <domain>Audiovisual Source Language Data</domain>
            <level>acceptable</level>
        </format>
        <format id="fGIF">
            <domain>Image Source Language Data</domain>
            <level>acceptable</level>
        </format>
        <format id="fGZIP">
            <domain>Packaging</domain>
            <level>acceptable</level>
            <comment>The archive should contain files in recommended formats.</comment>
        </format>
        <format id="fHTML">
            <domain>Textual Source Language Data</domain>
            <level>acceptable</level>
        </format>
        <format id="fHTML">
            <domain>Documentation</domain>
            <level>recommended</level>
        </format>
        <format id="fJPEG">
            <domain>Image Source Language Data</domain>
            <level>acceptable</level>
        </format>
        <format id="fJSON">
            <domain>Text Annotation</domain>
            <level>acceptable</level>
        </format>
        <format id="fJSON">
            <domain>Textual Source Language Data</domain>
            <level>acceptable</level>
        </format>
        <format id="fJSON">
            <domain>Metadata</domain>
            <level>acceptable</level>
        </format>
        <format id="fLaTeX">
            <domain>Documentation</domain>
            <level>acceptable</level>
        </format>
        <format id="fMarkdown">
            <domain>Textual Source Language Data</domain>
            <level>acceptable</level>
        </format>
        <format id="fMarkdown">
            <domain>Documentation</domain>
            <level>recommended</level>
        </format>
        <format id="fMKV">
            <domain>Audiovisual Source Language Data</domain>
            <level>acceptable</level>
        </format>
        <format id="fMP3">
            <domain>Audiovisual Source Language Data</domain>
            <level>acceptable</level>
        </format>
        <format id="fMP4">
            <domain>Audiovisual Source Language Data</domain>
            <level>acceptable</level>
        </format>
        <format id="fOGG">
            <domain>Audiovisual Source Language Data</domain>
            <level>discouraged</level>
        </format>
        <format id="fPDF">
            <domain>Textual Source Language Data</domain>
            <level>discouraged</level>
        </format>
        <format id="fPDF">
            <domain>Documentation</domain>
            <level>acceptable</level>
        </format>
        <format id="fTextPlain">
            <domain>Textual Source Language Data</domain>
            <level>recommended</level>
            <comment>UTF-8 encoding</comment>
        </format>
        <format id="fTextPlain">
            <domain>Documentation</domain>
            <level>acceptable</level>
        </format>
        <format id="fTextPlain">
            <domain>Audiovisual Annotation</domain>
            <level>discouraged</level>
        </format>
        <format id="fPNG">
            <domain>Image Source Language Data</domain>
            <level>acceptable</level>
        </format>
        <format id="fMOV">
            <domain>Audiovisual Source Language Data</domain>
            <level>acceptable</level>
        </format>
        <format id="fRAR">
            <domain>Packaging</domain>
            <level>discouraged</level>
        </format>
        <format id="fRTF">
            <domain>Textual Source Language Data</domain>
            <level>discouraged</level>
        </format>
        <format id="fRTF">
            <domain>Documentation</domain>
            <level>discouraged</level>
        </format>
        <format id="fSVG">
            <domain>Image Source Language Data</domain>
            <level>acceptable</level>
        </format>
        <format id="fTAR">
            <domain>Packaging</domain>
            <level>acceptable</level>
            <comment>The archive should contain files in recommended formats.</comment>
        </format>
        <format id="fTEI">
            <domain>Documentation</domain>
            <level>acceptable</level>
        </format>
        <format id="fTEI">
            <domain>Text Annotation</domain>
            <level>acceptable</level>
        </format>
        <format id="fTEI">
            <domain>Audiovisual Annotation</domain>
            <level>acceptable</level>
        </format>
        <format id="fTIFF">
            <domain>Image Source Language Data</domain>
            <level>acceptable</level>
        </format>
        <format id="fTRS">
            <domain>Audiovisual Annotation</domain>
            <level>acceptable</level>
        </format>
        <format id="fTSV">
            <domain>Text Annotation</domain>
            <level>acceptable</level>
        </format>
        <format id="fTSV">
            <domain>Metadata</domain>
            <level>acceptable</level>
        </format>
        <format id="fWAVE">
            <domain>Audiovisual Source Language Data</domain>
            <level>recommended</level>
        </format>
        <format id="fXML">
            <domain>Metadata</domain>
            <level>acceptable</level>
        </format>
        <format id="fXML">
            <domain>Documentation</domain>
            <level>acceptable</level>
        </format>
        <format id="fZIP">
            <domain>Packaging</domain>
            <level>recommended</level>
            <comment>The archive should contain files in recommended formats.</comment>
        </format>
    </formats>
</recommendation>
