=== clarin-eric/standards/SIS/clarin/schemas/recommendation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:annotation>
        <xs:documentation xml:lang="en">This schema defines the structure of the recommendation
            files that reside under data/recommendations/. Mostly auto-derived thru the magic of
            oXygen.</xs:documentation>
    </xs:annotation>
    <xs:element name="recommendation">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="header"/>
                <xs:element ref="formats"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="header">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="title" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="url" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="lastUpdateCommitID" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="exportDate" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="filter" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="title" type="xs:string"/>
    <xs:element name="url" type="xs:anyURI">
        <xs:annotation>
            <xs:documentation>Element inserted into exports, to document where they came from.</xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="lastUpdateCommitID" type="xs:string">
        <xs:annotation>
            <xs:documentation>Element auto-inserted upon committing the file into the repository. It
                will not appear in exports from aggregated lists in the SIS.</xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="exportDate" type="xs:string">
        <xs:annotation>
            <xs:documentation>Element present in exports from the SIS; it encodes a standardized
                date string of the export.</xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="filter">
        <xs:annotation>
            <xs:documentation>Element present in exports from aggregated and filtered lists in the
                SIS.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="centre" minOccurs="0"/>
                <xs:element ref="domain" minOccurs="0"/>
                <xs:element ref="level" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="centre" type="xs:string"/>
    <xs:element name="domain">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <!--Annotation-->
                <xs:enumeration value="Audiovisual Annotation">
                    <xs:annotation>
                        <xs:documentation>Annotations of audiovisual sources, usually including a
                            basic rendering of the spoken content (transcription) and sometimes
                            further annotation.</xs:documentation>
                    </xs:annotation>
                </xs:enumeration>
                <xs:enumeration value="Image Annotation">
                    <xs:annotation>
                        <xs:documentation>Annotations of image sources.</xs:documentation>
                    </xs:annotation>
                </xs:enumeration>
                <xs:enumeration value="Text Annotation">
                    <xs:annotation>
                        <xs:documentation>Annotations of textual sources/written text, with the
                            original text included or as stand-off.</xs:documentation>
                    </xs:annotation>
                </xs:enumeration>
                <!--Data/Resource Description-->
                <xs:enumeration value="Catalogue Metadata">
                    <xs:annotation>
                        <xs:documentation>Basic structured information for discoverability and
                            general description, to be openly provided for
                            harvesting.</xs:documentation>
                    </xs:annotation>
                </xs:enumeration>
                <xs:enumeration value="Contextual Information">
                    <xs:annotation>
                        <xs:documentation>Structured information on the communicative event or text
                            and its creators (i.e. participants or authors) relevant for
                            analysis.</xs:documentation>
                    </xs:annotation>
                </xs:enumeration>
                <xs:enumeration value="Documentation">
                    <xs:annotation>
                        <xs:documentation>Unstructured documentation of the resource and its parts
                            such as corpus or annotation guidelines.</xs:documentation>
                    </xs:annotation>
                </xs:enumeration>
                <xs:enumeration value="Metadata">
                    <xs:annotation>
                        <xs:documentation>Comprehensive structured information including
                            descriptive, structural and administrative metadata. See the National
                            Information Standards Organization primer on metadata for further
                            hints.</xs:documentation>
                    </xs:annotation>
                </xs:enumeration>
                <!--Databases-->
                <xs:enumeration value="Geodata">
                    <xs:annotation>
                        <xs:documentation>Information on geographic locations.</xs:documentation>
                    </xs:annotation>
                </xs:enumeration>
                <xs:enumeration value="Language Description">
                    <xs:annotation>
                        <xs:documentation>Structured or unstructured descriptions of linguistic
                            varieties or phenomena, typological databases, etc.</xs:documentation>
                    </xs:annotation>
                </xs:enumeration>
                <xs:enumeration value="Lexical Resource">
                    <xs:annotation>
                        <xs:documentation>Structured (item-based) resources for lexical and/or
                            conceptual information on units of language (e.g. wordlists, lexicons,
                            WordNets etc.)</xs:documentation>
                    </xs:annotation>
                </xs:enumeration>
                <xs:enumeration value="Statistical Data">
                    <xs:annotation>
                        <xs:documentation>Data from surveys and tests in numeric
                            formats.</xs:documentation>
                    </xs:annotation>
                </xs:enumeration>
                <!--Source Data-->
                <xs:enumeration value="Audiovisual Source Language Data">
                    <xs:annotation>
                        <xs:documentation>Audio or video recordings providing spoken/multimodal or
                            signed language data for research purposes.</xs:documentation>
                    </xs:annotation>
                </xs:enumeration>
                <xs:enumeration value="Contextual Data">
                    <xs:annotation>
                        <xs:documentation>Images (photos or drawings) or documents relevant to the
                            communicative event or text but not part of the source language
                            data.</xs:documentation>
                    </xs:annotation>
                </xs:enumeration>
                <xs:enumeration value="Image Source Language Data">
                    <xs:annotation>
                        <xs:documentation>Digitized images of analogue sources of written language
                            data for research purposes (e.g. facsimiles, scans of handwriting,
                            photos of inscriptions).</xs:documentation>
                    </xs:annotation>
                </xs:enumeration>
                <xs:enumeration value="Textual Source Language Data">
                    <xs:annotation>
                        <xs:documentation>Written unstructured/plain text or originally structured
                            text (e.g. HTML) without linguistic or other mark-up added for research
                            purposes.</xs:documentation>
                    </xs:annotation>
                </xs:enumeration>
                <!--Uncategorized-->
                <xs:enumeration value="Other">
                    <xs:annotation>
                        <xs:documentation>Any other function that cannot be included in an existing
                            domain. The content of this domain will be periodically examined for
                            potential patterns that may give rise to new domains.</xs:documentation>
                    </xs:annotation>
                </xs:enumeration>
                <xs:enumeration value="Tool Support">
                    <xs:annotation>
                        <xs:documentation>Tool-related formats required for specific functionality
                            of the tool or reliable reuse of resources (e.g. tagsets, annotation
                            schemes, vocabularies, language models, parameter files, and other
                            specifications or settings)</xs:documentation>
                    </xs:annotation>
                </xs:enumeration>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="level">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="recommended"/>
                <xs:enumeration value="acceptable"/>
                <xs:enumeration value="deprecated"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="formats">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="format"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="format">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="domain"/>
                <xs:element ref="level"/>
                <xs:element minOccurs="0" ref="comment"/>
            </xs:sequence>
            <xs:attribute name="id" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="comment">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="a"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="i"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="code"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="a">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="href" use="required" type="xs:anyURI"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="i">
        <xs:simpleType>
            <xs:restriction base="xs:string"/>
        </xs:simpleType>
    </xs:element>
    <xs:element name="code">
        <xs:simpleType>
            <xs:restriction base="xs:string"/>
        </xs:simpleType>
    </xs:element>
    
</xs:schema>

=== clarin-eric/standards/SIS/clarin/data/recommendations/CLARIN.SI-recommendation.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="../../schemas/recommendation.xsd" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?> 
<recommendation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../schemas/recommendation.xsd">
   <header>
      <lastUpdateCommitID>d4ad73e931b56f907716917299724fce4466f996</lastUpdateCommitID>
      <filter>
         <centreID>CLARIN.SI</centreID>
      </filter>
      <respStmt>
         <name>Jakob Lenardič</name>
         <resp><!--optionally specify the range of responsibility; useful if multiple respStmt are used--></resp>
         <link>https://github.com/jakoble</link>
         <reviewDate>2026-06-19</reviewDate>
      </respStmt>
      <centre id="CLARIN.SI" deposition="1">
         <centreName>CLARIN.SI Language Technology Centre, Slovenia</centreName>
         <registryLink registry="CLARIN" uri="https://centres.clarin.eu/centre/30"/>
         <nodeInfo>
            <ri status="B-centre">CLARIN</ri>
         </nodeInfo>
      </centre>
   </header>
   <info>
      <p>This page lists the file formats which are recommended for depositing in CLARIN.SI. For additional information, see 
         <a href="https://www.clarin.si/repository/xmlui/page/data">https://www.clarin.si/repository/xmlui/page/data</a>.</p>
      <p>For details on the preservation policy of CLARIN.SI, see 
         <a href="https://www.clarin.si/repository/xmlui/page/about#preservation-policy">https://www.clarin.si/repository/xmlui/page/about#preservation-policy</a>.</p>
   </info>
   <formats>
      <format id="fEXB">
         <domain>Audiovisual Annotation</domain>
         <level>recommended</level>
      </format>
      <format id="fEXS">
         <domain>Audiovisual Annotation</domain>
         <level>recommended</level>
      </format>
      <format id="fFLN">
         <domain>Audiovisual Annotation</domain>
         <level>recommended</level>
      </format>
      <format id="fTEISpoken">
         <domain>Audiovisual Annotation</domain>
         <level>recommended</level>
      </format>
      <format id="fTRS">
         <domain>Audiovisual Annotation</domain>
         <level>recommended</level>
      </format>
      <format id="fAIFF">
         <domain>Audiovisual Source Language Data</domain>
         <level>recommended</level>
      </format>
      <format id="fAVI">
         <domain>Audiovisual Source Language Data</domain>
         <level>recommended</level>
      </format>
      <format id="fFLAC">
         <domain>Audiovisual Source Language Data</domain>
         <level>recommended</level>
      </format>
      <format id="fM2J">
         <domain>Audiovisual Source Language Data</domain>
         <level>recommended</level>
      </format>
      <format id="fM4A">
         <domain>Audiovisual Source Language Data</domain>
         <level>recommended</level>
      </format>
      <format id="fMP3">
         <domain>Audiovisual Source Language Data</domain>
         <level>recommended</level>
      </format>
      <format id="fMP4">
         <domain>Audiovisual Source Language Data</domain>
         <level>recommended</level>
      </format>
      <format id="fMPEG1">
         <domain>Audiovisual Source Language Data</domain>
         <level>recommended</level>
      </format>
      <format id="fMPEG2">
         <domain>Audiovisual Source Language Data</domain>
         <level>recommended</level>
      </format>
      <format id="fRAW">
         <domain>Audiovisual Source Language Data</domain>
         <level>recommended</level>
      </format>
      <format id="fWAVE">
         <domain>Audiovisual Source Language Data</domain>
         <level>recommended</level>
      </format>
      <format id="fCMDI">
         <domain>Catalogue Metadata</domain>
         <level>recommended</level>
      </format>
      <format id="fHTML">
         <domain>Documentation</domain>
         <level>recommended</level>
      </format>
      <format id="fPDF">
         <domain>Documentation</domain>
         <level>recommended</level>
      </format>
      <format id="fTEI">
         <domain>Documentation</domain>
         <level>recommended</level>
      </format>
      <format id="fXML">
         <domain>Documentation</domain>
         <level>recommended</level>
      </format>
      <format id="fKML">
         <domain>Geodata</domain>
         <level>recommended</level>
      </format>
      <format id="fGIF">
         <domain>Image Source Language Data</domain>
         <level>recommended</level>
      </format>
      <format id="fJPEG">
         <domain>Image Source Language Data</domain>
         <level>recommended</level>
      </format>
      <format id="fPDF">
         <domain>Image Source Language Data</domain>
         <level>recommended</level>
      </format>
      <format id="fPNG">
         <domain>Image Source Language Data</domain>
         <level>recommended</level>
      </format>
      <format id="fSVG">
         <domain>Image Source Language Data</domain>
         <level>recommended</level>
      </format>
      <format id="fTIFF">
         <domain>Image Source Language Data</domain>
         <level>recommended</level>
      </format>
      <format id="fCSV">
         <domain>Lexical Resource</domain>
         <level>recommended</level>
      </format>
      <format id="fLMF">
         <domain>Lexical Resource</domain>
         <level>recommended</level>
      </format>
      <format id="fTSV">
         <domain>Lexical Resource</domain>
         <level>recommended</level>
      </format>
      <format id="fR">
         <domain>Statistical Data</domain>
         <level>recommended</level>
      </format>
      <format id="fCoNLL-U">
         <domain>Text Annotation</domain>
         <level>recommended</level>
      </format>
      <format id="fPDF">
         <domain>Text Annotation</domain>
         <level>discouraged</level>
      </format>
      <format id="fRDFXML">
         <domain>Text Annotation</domain>
         <level>recommended</level>
      </format>
      <format id="fTEI">
         <domain>Text Annotation</domain>
         <level>recommended</level>
      </format>
      <format id="fTiger">
         <domain>Text Annotation</domain>
         <level>recommended</level>
      </format>
      <format id="fXML">
         <domain>Text Annotation</domain>
         <level>recommended</level>
      </format>
      <format id="fePub">
         <domain>Textual Source Language Data</domain>
         <level>recommended</level>
      </format>
      <format id="fEAF">
         <domain>Textual Source Language Data</domain>
         <level>recommended</level>
      </format>
      <format id="fFoLiA">
         <domain>Textual Source Language Data</domain>
         <level>recommended</level>
      </format>
      <format id="fPartitur">
         <domain>Textual Source Language Data</domain>
         <level>recommended</level>
      </format>
      <format id="fPDF">
         <domain>Textual Source Language Data</domain>
         <level>discouraged</level>
      </format>
      <format id="fPraat">
         <domain>Textual Source Language Data</domain>
         <level>recommended</level>
      </format>
      <format id="fTCF">
         <domain>Textual Source Language Data</domain>
         <level>recommended</level>
      </format>
      <format id="fTextPlain">
         <domain>Textual Source Language Data</domain>
         <level>recommended</level>
      </format>
      <format id="fCSS">
         <domain>Tool Support</domain>
         <level>recommended</level>
      </format>
      <format id="fDTD">
         <domain>Tool Support</domain>
         <level>recommended</level>
      </format>
      <format id="fGZIP">
         <domain>Packaging</domain>
         <level>recommended</level>
      </format>
      <format id="fJS">
         <domain>Tool Support</domain>
         <level>recommended</level>
      </format>
      <format id="fTAR">
         <domain>Packaging</domain>
         <level>recommended</level>
      </format>
      <format id="fXSD">
         <domain>Tool Support</domain>
         <level>recommended</level>
      </format>
      <format id="fXSLT">
         <domain>Tool Support</domain>
         <level>recommended</level>
      </format>
      <format id="fZIP">
         <domain>Packaging</domain>
         <level>recommended</level>
      </format>
   </formats>
</recommendation>

=== clarin-eric/standards/SIS/clarin/data/recommendations/CLARIN-IS-recommendation.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="../../schemas/recommendation.xsd" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?> 
<recommendation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../schemas/recommendation.xsd">
    <header>
        <lastUpdateCommitID>bec52cd36a2996677ce07153a19ce774097f9130</lastUpdateCommitID>
        <filter>
            <centreID>CLARIN-IS</centreID>
        </filter>
        <respStmt>
            <name>Starkaður Barkarson</name>
            <link>https://github.com/starkadur</link>
            <reviewDate>2025-03-21</reviewDate>
        </respStmt>
        <centre id="CLARIN-IS" deposition="1">
        <centreName>CLARIN-IS (Árni Magnússon Institute for Icelandic Studies)</centreName>
        <registryLink registry="CLARIN" uri="https://centres.clarin.eu/centre/64"/>
        <nodeInfo>
          <ri status="B-centre">CLARIN</ri>
        </nodeInfo>
      </centre>
    </header>
    <info><!--use p, ul, ol elements here--></info>
    <formats><!--
            This template will assist in adjusting/creating a recommendations document if you don't
            have access to a schema-aware XML editor. Copy the XML fragment, 
            *  adjust the format ID (see https://clarin.ids-mannheim.de/standards/views/list-formats.xq ),
            *  adjust the domain (https://clarin.ids-mannheim.de/standards/views/list-domains.xq ),
            *  adjust the recommendation level ({ recommended, acceptable, discouraged }),
            *  repeat as necessary;
            *  submit the result as a PR against https://github.com/clarin-eric/standards/tree/formats .

       -->
        
        <format id="fMP3">
            <domain>Audiovisual Source Language Data</domain>
            <level>acceptable</level>
        </format>
        <format id="fAVI">
            <domain>Audiovisual Source Language Data</domain>
            <level>acceptable</level>
        </format>
        <format id="fMP4">
            <domain>Audiovisual Source Language Data</domain>
            <level>recommended</level>
        </format>        
        <format id="fOGG">
            <domain>Audiovisual Source Language Data</domain>
            <level>acceptable</level>
        </format>
        <format id="fMPEG">
            <domain>Audiovisual Source Language Data</domain>
            <level>recommended</level>
        </format>
        <format id="fEAF">
            <domain>Audiovisual Annotation</domain>
            <level>recommended</level>
        </format>

        <format id="fPDF">
            <domain>Documentation</domain>
            <level>recommended</level>
        </format>
        <format id="fTextPlain">
            <domain>Documentation</domain>
            <level>discouraged</level>
        </format>
        <format id="fTEI">
            <domain>Documentation</domain>
            <level>recommended</level>
        </format>
        <format id="fXML">
            <domain>Documentation</domain>
            <level>recommended</level>
        </format>

        <format id="fGIF">
            <domain>Image Source Language Data</domain>
            <level>recommended</level>
        </format>
        <format id="fJPEG">
            <domain>Image Source Language Data</domain>
            <level>recommended</level>
        </format>
        <format id="fPNG">
            <domain>Image Source Language Data</domain>
            <level>recommended</level>
        </format>
        <format id="fSVG">
            <domain>Image Source Language Data</domain>
            <level>recommended</level>
        </format>
        <format id="fTIFF">
            <domain>Image Source Language Data</domain>
            <level>recommended</level>
        </format>
        <format id="fXML">
            <domain>Lexical Resource</domain>
            <level>acceptable</level>
        </format>
        <format id="fLMF">
            <domain>Lexical Resource</domain>
            <level>recommended</level>
        </format>
        <format id="fCSV">
            <domain>Lexical Resource</domain>
            <level>recommended</level>
        </format>
        <format id="fTSV">
            <domain>Lexical Resource</domain>
            <level>recommended</level>
        </format>

        <format id="fR">
            <domain>Statistical Data</domain>
            <level>recommended</level>
        </format>
        <format id="fSPSS">
            <domain>Statistical Data</domain>
            <level>acceptable</level>
        </format>
      
        
        <format id="fTextPlain">
            <domain>Textual Source Language Data</domain>
            <level>recommended</level>
        </format>
        
        <format id="fCoNLL-U">
            <domain>Text Annotation</domain>
            <level>recommended</level>
        </format>
        <format id="fTEI">
            <domain>Text Annotation</domain>
            <level>recommended</level>
        </format>
        <format id="fXML">
            <domain>Text Annotation</domain>
            <level>acceptable</level>
        </format>
        <format id="fTEIHeader">
            <domain>Metadata</domain>
            <level>recommended</level>
        </format>
        <format id="fCMDI">
            <domain>Metadata</domain>
            <level>recommended</level>
        </format>
        <format id="fZIP">
            <domain>Packaging</domain>
            <level>recommended</level>
        </format>
        <format id="fTAR">
            <domain>Packaging</domain>
            <level>recommended</level>
        </format>
    </formats>
</recommendation>

=== clarin-eric/standards/SIS/clarin/data/recommendations/FIN-CLARIN-recommendation.xml
<recommendation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../schemas/recommendation.xsd">
    <header>
        <lastUpdateCommitID>147cb5ea659a5752efd819898b43da23e00c6a77</lastUpdateCommitID>
        <filter>
         <centre>FIN-CLARIN</centre>
      </filter>
    </header>
    <formats>
        <format id="fTEISpoken">
            <domain>Audiovisual Annotation</domain>
            <level>recommended</level>
        </format>
        <format id="fWave">
            <domain>Audiovisual Source Language Data</domain>
            <level>recommended</level>
        </format>
        <format id="fCMDI">
            <domain>Catalogue Metadata</domain>
            <level>recommended</level>
        </format>
        <format id="fPDFA">
            <domain>Documentation</domain>
            <level>recommended</level>
        </format>
        <format id="fTEI">
            <domain>Documentation</domain>
            <level>recommended</level>
        </format>
        <format id="fXML">
            <domain>Documentation</domain>
            <level>recommended</level>
        </format>
        <format id="fJP2">
            <domain>Image Source Language Data</domain>
            <level>recommended</level>
        </format>
        <format id="fJPEG">
            <domain>Image Source Language Data</domain>
            <level>recommended</level>
        </format>
        <format id="fPNG">
            <domain>Image Source Language Data</domain>
            <level>recommended</level>
        </format>
        <format id="fSVG">
            <domain>Image Source Language Data</domain>
            <level>recommended</level>
        </format>
        <format id="fCSV">
            <domain>Lexical Resource</domain>
            <level>recommended</level>
        </format>
        <format id="fLMF">
            <domain>Lexical Resource</domain>
            <level>recommended</level>
        </format>
        <format id="fCoNLL-U">
            <domain>Text Annotation</domain>
            <level>recommended</level>
        </format>
        <format id="fTEI">
            <domain>Text Annotation</domain>
            <level>recommended</level>
        </format>
        <format id="fXML">
            <domain>Text Annotation</domain>
            <level>recommended</level>
        </format>
        <format id="fELAN">
            <domain>Textual Source Language Data</domain>
            <level>recommended</level>
        </format>
        <format id="fPDFA">
            <domain>Textual Source Language Data</domain>
            <level>acceptable</level>
        </format>
        <format id="fPraat">
            <domain>Textual Source Language Data</domain>
            <level>recommended</level>
        </format>
        <format id="fTextPlain">
            <domain>Textual Source Language Data</domain>
            <level>recommended</level>
        </format>
        <format id="fGZIP">
            <domain>Tool Support</domain>
            <level>recommended</level>
        </format>
        <format id="fTAR">
            <domain>Tool Support</domain>
            <level>recommended</level>
        </format>
        <format id="fZIP">
            <domain>Tool Support</domain>
            <level>recommended</level>
        </format>
    </formats>
</recommendation>
